apiVersion: v1
kind: Pod
metadata:
  name: lab601-nodejs-external
  labels:
    app: lab601
spec:
  containers:
    - name: hellocontainer
      image: ignitiontraining/lab601nodejs:1.0
      imagePullPolicy: Always
      resources:
        limits:
          memory: 30Mi
      ports:
        - name: greeting-port
          containerPort: 4574
      env:
      - name: LISTEN_PORT
        value: "4574"
      - name: GREETING
        value: Selam



