apiVersion: v1
kind: Pod
metadata:
  name: lab601-nodejs
  labels:
    app: lab601
spec:
  imagePullSecrets:
  - name: regcred
  containers:
    - name: hellocontainer
      image: k8s.ignition-training.com/user111/nodejs601:1.0
      imagePullPolicy: Always
      resources:
        limits:
          memory: 30Mi
      ports:
        - name: greeting-port
          containerPort: 4574 
      env:
      - name: LISTEN_PORT
        value: "4574"
      - name: GREETING
        value: Selam



