# Remember to change the repository 
apiVersion: v1
kind: Pod
metadata:
  name: lab601-nodejs
  labels:
    app: hello 
spec:
  containers:
    - name: hellocontainer
      image: registry.k8s.igntnlabs.com:9443/testuser8/lab601nodejs:1.0
      imagePullPolicy: Always
      resources:
        limits:
          memory: 30Mi
      env:
      - name: LISTEN_PORT
        value: "4545"
      - name: GREETING
        value: Selam
      ports:
        - name: greeting-port
          containerPort: 4545


