apiVersion: v1
kind: Pod
metadata:
  name: lab501-python
  labels:
    app: lab501
spec:
  imagePullSecrets:
  - name: regcred
  containers:
    - name: hellocontainer
      image: k8s.ignition-training.com/user111/python501:1.0
      imagePullPolicy: Always
      resources:
        limits:
          memory: 30Mi
      ports:
        - name: greeting-port
          containerPort: 4574


