# Remember to change the user in the repository name
apiVersion: v1
kind: Pod
metadata:
  name: lab501-nodejs
  labels:
    app: hello 
spec:
  containers:
    - name: hellocontainer
      image: registry.k8s.igntnlabs.com:9443/testuser8/lab501nodejs:1.0
      imagePullPolicy: Always
      resources:
        limits:
          memory: 30Mi
      ports:
        - name: greeting-port
          containerPort: 4574


