apiVersion: v1
kind: Pod
metadata:
  name: lab501-go
  labels:
    app: hello 
spec:
  imagePullSecrets:
  - name: regcred
  containers:
    - name: hellocontainer
      image: k8s.ignition-training.com/user111/lab501go:1.0
      imagePullPolicy: Always
      resources:
        limits:
          memory: 120Mi
      ports:
        - name: greeting-port
          containerPort: 4574


