apiVersion: v1
kind: Pod
metadata:
  name: lab601-python-external
  labels:
    app: hello
spec:
  containers:
    - name: hellocontainer
      image: ignitiontraining/lab601python:1.0
      imagePullPolicy: Always
      resources:
        limits:
          memory: 30Mi
      env:
      - name: LISTEN_PORT
        value: "4545"
      - name: GREETING
        value: Tardias
      ports:
        - name: greeting-port
          containerPort: 4545


