# Remember to change the repository to match your user
apiVersion: v1
kind: Pod
metadata:
  name: lab602-nodejs
  labels:
    app: hello 
spec:
  containers:
    - name: hellocontainer
      image: registry.k8s.igntnlabs.com:9443/testuser8/lab601nodejs:1.0
      imagePullPolicy: Always
      resources:
        limits:
          memory: 30Mi
      envFrom:
      - configMapRef:
          name: lab602-config
      ports:
        - name: greeting-port
          containerPort: 4545


