apiVersion: v1
kind: Pod
metadata:
  name: lab602-nodejs
  labels:
    app: hello 
spec:
  imagePullSecrets:
  - name: regcred
  containers:
    - name: hellocontainer
      image: k8s.ignition-training.com/user111/lab601nodejs:1.0
      imagePullPolicy: Always
      resources:
        limits:
          memory: 30Mi
      envFrom:
      - configMapRef:
          name: lab602-config
        value: Selam
      ports:
        - name: greeting-port
          containerPort: 4545


