apiVersion: apps/v1
kind: Deployment 
metadata:
  name: lab701-nodejs
  labels:
    app: hello 
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hello
  template:
    metadata:
      labels:
        app: hello
    spec:
      volumes:
      - name: config-volume
        configMap:
          name: lab602-config 
      containers:
        - name: hellocontainer
          image: k8s.ignition-training.com/user111/lab701nodejs:1.0
          imagePullPolicy: Always
          resources:
            limits:
              memory: 30Mi
          envFrom:                 # This will bring in more variables than we use, no problem though
          - configMapRef:
              name: lab602-config 
          env:
          - name: GREETING_LOCATION
            value: /data/GREETING
          - name: RANDOMLY_ADDED_VAR
            value: ThisTriggersRolloutWhenNew 
          ports:
            - name: greeting-port
              containerPort: 4545
          volumeMounts:
          - name: config-volume
            mountPath: /data
            readOnly: true


