apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: hello-labrole-binding 
subjects:
- kind: ServiceAccount 
  name: helloaccount 
roleRef:
  kind: Role
  name: labrole 
  apiGroup: rbac.authorization.k8s.io
