# You will need to change the namespace
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: labrole
  namespace: testuser8 
rules:
- apiGroups: [""]
  resources: ["pods", "services"]
  verbs: ["get", "list"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list"]
